# Generated by Django 5.1.3 on 2024-11-24 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='produto.categoria'),
            preserve_default=False,
        ),
    ]
